import {
  calculateCompoundInterest,
  COMPOUNDING_PERIODS_PER_YEAR,
  type CompoundingFrequency,
} from "./CompoundInterestCalculator";

const MAX_BISECTION_ITERATIONS = 60;
const RETURN_RATE_LOWER_BOUND_PERCENT = -99;
const RETURN_RATE_UPPER_BOUND_PERCENT = 1000;

/**
 * Solves for the number of years needed to reach `targetAmount`, stepping the same
 * month-by-month simulation `calculateCompoundInterest` uses until the balance meets
 * the target. Balance is monotonically non-decreasing in time (principal and
 * contributions never shrink the balance across a month), so the first month the
 * target is met is unambiguous — this is exact, not an approximation.
 *
 * Returns `null` if the target is not reached within `maxYears` (e.g. contributions
 * and rate are both too small relative to the target).
 */
export function solveInvestmentLength(
  targetAmount: number,
  principal: number,
  annualRatePercent: number,
  frequency: CompoundingFrequency,
  monthlyContribution = 0,
  maxYears = 100
): number | null {
  if (!Number.isFinite(targetAmount) || targetAmount <= 0) return null;
  if (principal >= targetAmount) return 0;

  const periodsPerYear = COMPOUNDING_PERIODS_PER_YEAR[frequency];
  const annualRate = annualRatePercent / 100;
  const monthlyRate = annualRate === 0 ? 0 : Math.pow(1 + annualRate / periodsPerYear, periodsPerYear / 12) - 1;
  const contribution = Math.max(monthlyContribution, 0);

  let balance = principal;
  const maxMonths = Math.round(maxYears * 12);

  for (let month = 1; month <= maxMonths; month++) {
    balance += balance * monthlyRate;
    balance += contribution;
    if (balance >= targetAmount) return month / 12;
  }

  return null;
}

/**
 * Solves for the constant annual return rate needed to reach `targetAmount` by
 * `years`, via bisection on `calculateCompoundInterest`'s future value — which is
 * monotonically increasing in rate for any rate above -100%. Bisection converges to
 * within a small fraction of a basis point well inside `MAX_BISECTION_ITERATIONS`.
 *
 * Returns `null` if the target isn't achievable within the search bounds
 * (-99% to 1000% annual return).
 */
export function solveReturnRate(
  targetAmount: number,
  principal: number,
  years: number,
  frequency: CompoundingFrequency,
  monthlyContribution = 0
): number | null {
  if (!Number.isFinite(targetAmount) || targetAmount <= 0 || years <= 0) return null;

  const futureValueAt = (ratePercent: number) =>
    calculateCompoundInterest(principal, ratePercent, years, frequency, monthlyContribution).futureValue;

  let low = RETURN_RATE_LOWER_BOUND_PERCENT;
  let high = RETURN_RATE_UPPER_BOUND_PERCENT;

  if (futureValueAt(low) > targetAmount) return null;
  if (futureValueAt(high) < targetAmount) return null;

  for (let i = 0; i < MAX_BISECTION_ITERATIONS; i++) {
    const mid = (low + high) / 2;
    if (futureValueAt(mid) < targetAmount) {
      low = mid;
    } else {
      high = mid;
    }
  }

  return (low + high) / 2;
}

/**
 * Solves for the starting principal needed to reach `targetAmount`. Exact, closed-form:
 * `calculateCompoundInterest`'s future value is exactly linear in principal (each
 * month's interest is a linear function of the running balance), so the future value
 * contributed by a unit principal — computed once — scales the whole answer directly.
 */
export function solveStartingAmount(
  targetAmount: number,
  annualRatePercent: number,
  years: number,
  frequency: CompoundingFrequency,
  monthlyContribution = 0
): number {
  if (!Number.isFinite(targetAmount) || years <= 0) return 0;

  const futureValueFromContributionsAlone = calculateCompoundInterest(
    0,
    annualRatePercent,
    years,
    frequency,
    monthlyContribution
  ).futureValue;
  const futureValuePerUnitPrincipal = calculateCompoundInterest(1, annualRatePercent, years, frequency, 0).futureValue;

  if (futureValuePerUnitPrincipal <= 0) return 0;

  const requiredPrincipal = (targetAmount - futureValueFromContributionsAlone) / futureValuePerUnitPrincipal;
  return Math.max(requiredPrincipal, 0);
}

/**
 * Solves for the monthly contribution needed to reach `targetAmount`. Exact, closed-form:
 * the future value generated by monthly contributions is exactly linear in the
 * contribution amount (every month uses the same contribution, each compounding
 * independently), so the future value generated by a unit ($1/month) contribution —
 * computed once — scales the whole answer directly.
 */
export function solveAdditionalContribution(
  targetAmount: number,
  principal: number,
  annualRatePercent: number,
  years: number,
  frequency: CompoundingFrequency
): number {
  if (!Number.isFinite(targetAmount) || years <= 0) return 0;

  const futureValueFromPrincipalAlone = calculateCompoundInterest(principal, annualRatePercent, years, frequency, 0).futureValue;
  const futureValuePerUnitContribution = calculateCompoundInterest(0, annualRatePercent, years, frequency, 1).futureValue;

  if (futureValuePerUnitContribution <= 0) return 0;

  const requiredContribution = (targetAmount - futureValueFromPrincipalAlone) / futureValuePerUnitContribution;
  return Math.max(requiredContribution, 0);
}
