import {
  Atom,
  Axis3D,
  BrainCircuit,
  Calculator,
  CalendarClock,
  CloudSun,
  Code2,
  Dices,
  FileText,
  FlaskConical,
  Folder,
  GraduationCap,
  Globe,
  HeartPulse,
  PartyPopper,
  PiggyBank,
  Receipt,
  RefreshCw,
  Sigma,
  Spline,
  TrendingUp,
  Variable,
  type LucideIcon,
} from "lucide-react";

export const categoryIcons: Record<string, LucideIcon> = {
  calculator: Calculator,
  "brain-circuit": BrainCircuit,
  refresh: RefreshCw,
  code: Code2,
  text: FileText,
  folder: Folder,
  "trending-up": TrendingUp,
  sigma: Sigma,
  "heart-pulse": HeartPulse,
  globe: Globe,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  atom: Atom,
  flask: FlaskConical,
  "graduation-cap": GraduationCap,
  "calendar-clock": CalendarClock,
  "cloud-sun": CloudSun,
  "party-popper": PartyPopper,
  variable: Variable,
  spline: Spline,
  dices: Dices,
  "axis-3d": Axis3D,
};

export function getCategoryIcon(icon: string): LucideIcon {
  return categoryIcons[icon] ?? Calculator;
}
