/**
 * Tool slugs with a built /docs/[slug] page, rolled out category by category
 * (see ROADMAP.md). Single source of truth shared by the [slug] route (which
 * tool to render, and which slugs are real vs. 404), the sidebar nav (which
 * links show a "Soon" badge), and the /docs index page (which tools to list
 * as already available).
 */
export const DOCUMENTED_TOOL_SLUGS = [
  "compound-interest-calculator",
  "loan-calculator",
  "affordable-loan-calculator",
  "retirement-calculator",
  "house-affordability-calculator",
  "debt-to-income-calculator",
  "mortgage-calculator",
  "percentage-calculator",
  "gcf-lcm-calculator",
  "fraction-calculator",
  "scientific-notation-converter",
  "significant-figures-calculator",
  "area-calculator",
  "surface-area-calculator",
  "volume-calculator",
  "circle-calculator",
  "triangle-calculator",
  "statistics-calculator",
  "mean-median-mode-range-calculator",
  "standard-deviation-calculator",
  "probability-calculator",
  "random-number-generator",
  "scientific-calculator",
  "step-by-step-math-solver",
  "matrix-calculator",
  "vector-calculator",
  "graphing-calculator",
  "notepad-calculator",
  "multiplication-table-generator",
  "tip-calculator",
  "discount-calculator",
  "sales-tax-calculator",
  "invoice-generator",
  "inventory-valuation-calculator",
  "break-even-calculator",
  "fuel-cost-calculator",
  "batch-invoice-calculator",
  "tdee-calculator",
  "bmi-calculator",
  "ideal-weight-calculator",
  "target-heart-rate-calculator",
  "sleep-calculator",
  "body-fat-calculator",
  "due-date-calculator",
  "ovulation-calculator",
  "pregnancy-calculator",
  "macro-calculator",
  "bmr-calculator",
  "pace-calculator",
  "density-calculator",
  "ohms-law-calculator",
  "energy-work-power-calculator",
  "kinematics-calculator",
  "force-calculator",
  "projectile-motion-calculator",
  "ph-calculator",
  "molarity-calculator",
  "ideal-gas-law-calculator",
  "chemical-equation-balancer",
  "stoichiometry-calculator",
  "molar-mass-calculator",
  "json-formatter",
  "base64-tool",
  "password-generator",
  "barcode-generator",
  "color-palette-generator",
  "qr-code-generator",
  "pdf-merge-split",
  "zip-compressor",
  "csv-json-converter",
  "file-size-converter",
  "file-name-sanitizer",
  "duplicate-line-remover",
];

export function isToolDocumented(slug: string): boolean {
  return DOCUMENTED_TOOL_SLUGS.includes(slug);
}
