/**
 * Real captured pixel dimensions of each tool's primary above-the-fold
 * indicator card (the first `.rounded-2xl` result card inside the
 * `ToolAboveFold` result column — see the capture note in
 * TooloraLabs-Claude-Instructions.md §34), used to size the indicator
 * image column in DecoratedToolCard's hover overlay so it fills that
 * column completely with zero crop and zero letterboxing, regardless of
 * how tall or short a given tool's own result card naturally is.
 *
 * Covers all 101 tools (captured 2026-09-30). A tool missing here (a
 * future tool added without a matching capture) falls back to
 * DEFAULT_ASPECT_RATIO rather than breaking the build.
 */

const TOOL_INDICATOR_DIMENSIONS: Record<string, { width: number; height: number }> = {
  "affordable-loan-calculator": { width: 416, height: 573 },
  "age-calculator": { width: 416, height: 685 },
  "area-calculator": { width: 416, height: 417 },
  "barcode-generator": { width: 416, height: 370 },
  "base64-tool": { width: 416, height: 204 },
  "batch-invoice-calculator": { width: 416, height: 185 },
  "bmi-calculator": { width: 416, height: 627 },
  "bmr-calculator": { width: 416, height: 590 },
  "body-fat-calculator": { width: 416, height: 272 },
  "break-even-calculator": { width: 416, height: 1030 },
  "chemical-equation-balancer": { width: 416, height: 416 },
  "circle-calculator": { width: 416, height: 504 },
  "citation-generator": { width: 416, height: 268 },
  "class-schedule-builder": { width: 416, height: 724 },
  "color-palette-generator": { width: 416, height: 294 },
  "commodities-tracker": { width: 416, height: 435 },
  "compound-interest-calculator": { width: 416, height: 601 },
  "countdown-to-event-calculator": { width: 416, height: 463 },
  "crypto-converter": { width: 416, height: 347 },
  "csv-json-converter": { width: 416, height: 427 },
  "date-calculator": { width: 416, height: 371 },
  "debt-to-income-calculator": { width: 416, height: 575 },
  "density-calculator": { width: 416, height: 1158 },
  "dice-roller": { width: 416, height: 255 },
  "discount-calculator": { width: 416, height: 612 },
  "due-date-calculator": { width: 416, height: 400 },
  "duplicate-line-remover": { width: 416, height: 204 },
  "energy-work-power-calculator": { width: 416, height: 722 },
  "file-name-sanitizer": { width: 416, height: 204 },
  "file-size-converter": { width: 416, height: 204 },
  "force-calculator": { width: 416, height: 626 },
  "forex-converter": { width: 416, height: 347 },
  "fraction-calculator": { width: 416, height: 342 },
  "fuel-cost-calculator": { width: 416, height: 1130 },
  "gcf-lcm-calculator": { width: 416, height: 301 },
  "gpa-calculator": { width: 416, height: 675 },
  "graphing-calculator": { width: 416, height: 739 },
  "house-affordability-calculator": { width: 416, height: 552 },
  "ideal-gas-law-calculator": { width: 416, height: 887 },
  "ideal-weight-calculator": { width: 416, height: 409 },
  "image-converter": { width: 416, height: 204 },
  "inventory-valuation-calculator": { width: 416, height: 730 },
  "invoice-generator": { width: 416, height: 776 },
  "json-formatter": { width: 416, height: 501 },
  "kinematics-calculator": { width: 416, height: 862 },
  "loan-calculator": { width: 416, height: 555 },
  "lorem-ipsum-generator": { width: 416, height: 557 },
  "love-calculator": { width: 416, height: 146 },
  "macro-calculator": { width: 416, height: 530 },
  "matrix-calculator": { width: 416, height: 820 },
  "mean-median-mode-range-calculator": { width: 416, height: 545 },
  "molar-mass-calculator": { width: 416, height: 642 },
  "molarity-calculator": { width: 416, height: 774 },
  "mortgage-calculator": { width: 416, height: 605 },
  "multiplication-table-generator": { width: 416, height: 548 },
  "notepad-calculator": { width: 416, height: 329 },
  "ohms-law-calculator": { width: 416, height: 1216 },
  "ovulation-calculator": { width: 416, height: 642 },
  "pace-calculator": { width: 416, height: 439 },
  "password-generator": { width: 416, height: 565 },
  "pdf-merge-split": { width: 416, height: 184 },
  "percentage-calculator": { width: 416, height: 351 },
  "ph-calculator": { width: 416, height: 971 },
  "pregnancy-calculator": { width: 416, height: 556 },
  "probability-calculator": { width: 416, height: 333 },
  "projectile-motion-calculator": { width: 416, height: 971 },
  "qr-code-generator": { width: 416, height: 515 },
  "random-number-generator": { width: 416, height: 428 },
  "random-quote-generator": { width: 416, height: 376 },
  "readability-score-calculator": { width: 416, height: 369 },
  "reading-time-calculator": { width: 416, height: 122 },
  "retirement-calculator": { width: 416, height: 619 },
  "roman-numeral-converter": { width: 416, height: 196 },
  "sales-tax-calculator": { width: 416, height: 580 },
  "scientific-calculator": { width: 416, height: 618 },
  "scientific-notation-converter": { width: 416, height: 452 },
  "significant-figures-calculator": { width: 416, height: 321 },
  "sleep-calculator": { width: 416, height: 711 },
  "speech-to-text": { width: 416, height: 290 },
  "speech-word-count-calculator": { width: 416, height: 146 },
  "spelling-grammar-checker": { width: 416, height: 122 },
  "standard-deviation-calculator": { width: 416, height: 964 },
  "statistics-calculator": { width: 416, height: 592 },
  "step-by-step-math-solver": { width: 416, height: 326 },
  "stoichiometry-calculator": { width: 416, height: 480 },
  "study-time-calculator": { width: 416, height: 678 },
  "surface-area-calculator": { width: 416, height: 417 },
  "target-heart-rate-calculator": { width: 416, height: 414 },
  "tdee-calculator": { width: 416, height: 475 },
  "text-logo-generator": { width: 416, height: 656 },
  "text-to-speech": { width: 416, height: 214 },
  "time-calculator": { width: 416, height: 544 },
  "tip-calculator": { width: 416, height: 696 },
  "triangle-calculator": { width: 416, height: 607 },
  "unit-converter": { width: 416, height: 671 },
  "vector-calculator": { width: 416, height: 675 },
  "volume-calculator": { width: 416, height: 417 },
  "weather-forecast": { width: 416, height: 580 },
  "word-counter": { width: 416, height: 204 },
  "world-time-converter": { width: 416, height: 447 },
  "zip-compressor": { width: 416, height: 204 },
};

const DEFAULT_ASPECT_RATIO = "416 / 550";

export function getToolIndicatorAspectRatio(slug: string): string {
  const dims = TOOL_INDICATOR_DIMENSIONS[slug];
  return dims ? `${dims.width} / ${dims.height}` : DEFAULT_ASPECT_RATIO;
}
