import {
  Atom,
  Banknote,
  Binary,
  Bitcoin,
  BookOpen,
  Boxes,
  Braces,
  ArrowRightLeft,
  Calendar,
  CalendarClock,
  Grid3x3,
  Clock,
  CloudSun,
  Divide,
  Equal,
  Flame,
  FilePen,
  FileArchive,
  FileSpreadsheet,
  FileText,
  FlaskConical,
  Gem,
  GraduationCap,
  HandCoins,
  HardDrive,
  Home,
  House,
  Image,
  KeyRound,
  Landmark,
  Palette,
  ListX,
  Percent,
  PiggyBank,
  QrCode,
  Quote,
  Ratio,
  MoveUpRight,
  ScanBarcode,
  Superscript,
  Crosshair,
  TestTube,
  ChartColumn,
  Beaker,
  Gauge,
  Activity,
  MoveRight,
  Magnet,
  Rocket,
  Receipt,
  ReceiptText,
  Ruler,
  Scale,
  Sigma,
  Tag,
  Timer,
  Target,
  TrendingUp,
  Type,
  Wallet,
  Weight,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const toolIcons: Record<string, LucideIcon> = {
  "scientific-calculator": Sigma,
  "fraction-calculator": Divide,
  "scientific-notation-converter": Superscript,
  "significant-figures-calculator": Crosshair,
  "gpa-calculator": GraduationCap,
  "density-calculator": FlaskConical,
  "ohms-law-calculator": Zap,
  "ph-calculator": TestTube,
  "statistics-calculator": ChartColumn,
  "molarity-calculator": Beaker,
  "ideal-gas-law-calculator": Gauge,
  "energy-work-power-calculator": Activity,
  "kinematics-calculator": MoveRight,
  "force-calculator": Magnet,
  "projectile-motion-calculator": Rocket,
  "readability-score-calculator": BookOpen,
  "study-time-calculator": Timer,
  "vector-calculator": MoveUpRight,
  "matrix-calculator": Grid3x3,
  "molar-mass-calculator": Atom,
  "stoichiometry-calculator": ArrowRightLeft,
  "chemical-equation-balancer": Equal,
  "class-schedule-builder": CalendarClock,
  "citation-generator": Quote,
  "age-calculator": Calendar,
  "bmi-calculator": Scale,
  "ideal-weight-calculator": Weight,
  "mortgage-calculator": Home,
  "percentage-calculator": Percent,
  "tip-calculator": HandCoins,
  "discount-calculator": Tag,
  "sales-tax-calculator": Receipt,
  "image-converter": Image,
  "json-formatter": Braces,
  "color-palette-generator": Palette,
  "password-generator": KeyRound,
  "unit-converter": Ruler,
  "qr-code-generator": QrCode,
  "barcode-generator": ScanBarcode,
  "word-counter": Type,
  "base64-tool": Binary,
  "pdf-merge-split": FileText,
  "zip-compressor": FileArchive,
  "csv-json-converter": FileSpreadsheet,
  "file-size-converter": HardDrive,
  "file-name-sanitizer": FilePen,
  "duplicate-line-remover": ListX,
  "invoice-generator": ReceiptText,
  "inventory-valuation-calculator": Boxes,
  "break-even-calculator": Target,
  "crypto-converter": Bitcoin,
  "forex-converter": Banknote,
  "commodities-tracker": Gem,
  "weather-forecast": CloudSun,
  "tdee-calculator": Flame,
  "compound-interest-calculator": TrendingUp,
  "loan-calculator": Landmark,
  "affordable-loan-calculator": Wallet,
  "retirement-calculator": PiggyBank,
  "house-affordability-calculator": House,
  "debt-to-income-calculator": Ratio,
  "world-time-converter": Clock,
};

export function getToolIcon(slug: string): LucideIcon {
  return toolIcons[slug] ?? Wrench;
}
