import {
  Banknote,
  Binary,
  Bitcoin,
  Boxes,
  Braces,
  Calendar,
  Clock,
  CloudSun,
  Divide,
  Flame,
  FilePen,
  FileArchive,
  FileSpreadsheet,
  FileText,
  Gem,
  HandCoins,
  HardDrive,
  Home,
  House,
  Image,
  KeyRound,
  Landmark,
  Palette,
  ListX,
  Percent,
  PiggyBank,
  QrCode,
  Ratio,
  ScanBarcode,
  Receipt,
  ReceiptText,
  Ruler,
  Scale,
  Sigma,
  Tag,
  Target,
  TrendingUp,
  Type,
  Wallet,
  Weight,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const toolIcons: Record<string, LucideIcon> = {
  "scientific-calculator": Sigma,
  "fraction-calculator": Divide,
  "age-calculator": Calendar,
  "bmi-calculator": Scale,
  "ideal-weight-calculator": Weight,
  "mortgage-calculator": Home,
  "percentage-calculator": Percent,
  "tip-calculator": HandCoins,
  "discount-calculator": Tag,
  "sales-tax-calculator": Receipt,
  "image-converter": Image,
  "json-formatter": Braces,
  "color-palette-generator": Palette,
  "password-generator": KeyRound,
  "unit-converter": Ruler,
  "qr-code-generator": QrCode,
  "barcode-generator": ScanBarcode,
  "word-counter": Type,
  "base64-tool": Binary,
  "pdf-merge-split": FileText,
  "zip-compressor": FileArchive,
  "csv-json-converter": FileSpreadsheet,
  "file-size-converter": HardDrive,
  "file-name-sanitizer": FilePen,
  "duplicate-line-remover": ListX,
  "invoice-generator": ReceiptText,
  "inventory-valuation-calculator": Boxes,
  "break-even-calculator": Target,
  "crypto-converter": Bitcoin,
  "forex-converter": Banknote,
  "commodities-tracker": Gem,
  "weather-forecast": CloudSun,
  "tdee-calculator": Flame,
  "compound-interest-calculator": TrendingUp,
  "loan-calculator": Landmark,
  "affordable-loan-calculator": Wallet,
  "retirement-calculator": PiggyBank,
  "house-affordability-calculator": House,
  "debt-to-income-calculator": Ratio,
  "world-time-converter": Clock,
};

export function getToolIcon(slug: string): LucideIcon {
  return toolIcons[slug] ?? Wrench;
}
