import {
  Banknote,
  Binary,
  Bitcoin,
  Boxes,
  Braces,
  Calendar,
  FilePen,
  FileSpreadsheet,
  HandCoins,
  HardDrive,
  Home,
  Image,
  KeyRound,
  ListX,
  Percent,
  QrCode,
  Receipt,
  ReceiptText,
  Ruler,
  Scale,
  Sigma,
  Tag,
  Target,
  Type,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const toolIcons: Record<string, LucideIcon> = {
  "scientific-calculator": Sigma,
  "age-calculator": Calendar,
  "bmi-calculator": Scale,
  "mortgage-calculator": Home,
  "percentage-calculator": Percent,
  "tip-calculator": HandCoins,
  "discount-calculator": Tag,
  "sales-tax-calculator": Receipt,
  "image-converter": Image,
  "json-formatter": Braces,
  "password-generator": KeyRound,
  "unit-converter": Ruler,
  "qr-code-generator": QrCode,
  "word-counter": Type,
  "base64-tool": Binary,
  "csv-json-converter": FileSpreadsheet,
  "file-size-converter": HardDrive,
  "file-name-sanitizer": FilePen,
  "duplicate-line-remover": ListX,
  "invoice-generator": ReceiptText,
  "inventory-valuation-calculator": Boxes,
  "break-even-calculator": Target,
  "crypto-converter": Bitcoin,
  "forex-converter": Banknote,
};

export function getToolIcon(slug: string): LucideIcon {
  return toolIcons[slug] ?? Wrench;
}
